### ISSUE TITLE
Bug when  running the tool

### ISSUE THREAD

**Issue by TH3xACE** [mbrg/power-pwn#42]
When I  try to logon for the devicelogin step, I get this error:

AADSTS900561: The endpoint only accepts POST requests. Received a GET request.

**Comment by AvishaiEZen** [comment]
Hi @TH3xACE, 
1. It seems that this Microsoft error is possibly related to the client used for reaching the logon device URL (`https://microsoft.com/devicelogin`). If this is not what you meant, please elaborate.
2. The best way to test this again using a clean browser profile with no extensions and with no prior cache & cookies (or incognito).

Could you please test and update? Alternatively, please provide more details about your browser/client, since it might be affecting the request and generating the error you received.

Please LMK if you have any Qs or if I misunderstood.

Thanks,
Avishai

**Comment by AvishaiEZen** [comment]
Closing the issue, since there's been no response. Please let us know if you have any further Qs.
Thanks
