### ISSUE TITLE
vulnerable test power platform and copilots resources.

### ISSUE THREAD

**Issue by cheahengsoon** [mbrg/power-pwn#70]
Hi Team,

May I get the vulnerable test power platform and copilots resources for powerpwn?

Thank you

**Comment by AvishaiEZen** [comment]
Hi @cheahengsoon, 
1. We're planning to develop such test resources and will update when we do.
2. Can you share some more info about what you were thinking of testing ATM? For some scenarios, a connection would be enough to start seeing results with powerpwn (e.g., you want to see what resources a certain user has access to with the recon/powerdump modules).
3. If you want to lean more about how vulnerable resources are created in order to test your tenant, please also feel free to check out the following resources:
  - [Zenity Labs](https://labs.zenity.io/)
  - [The Zenity Blog](https://zenity.io/blog)
  - [The 'All You Need Is Guest' Black Hat talk](https://www.youtube.com/watch?v=dmbRpwP5L9s)
  - [The GenAI Attacks Matrix](https://ttps.ai/)

Please LMK if you need any other info.
Thanks!

**Comment by AvishaiEZen** [comment]
Closing the issue, since there's been no response. Please let us know if you have any further Qs.
Thanks
